cxx_library(
    name = "logger",
    srcs = [
        "Logger.cpp",
    ],
    headers = [],
    exported_headers = [
        "Logger.h",
    ],
    header_namespace = "logger",
    link_style = "shared",
    preferred_linkage = "shared",
    deps = [
        "//utils:builtin-color-util",
    ],
    visibility = [
        "//examples:testdrive"
    ],
    labels = [],
)
