# test driver
cxx_binary(
    name = "testdrive",
    srcs = [
        "main.cpp",
    ],
    link_style = "shared",
    deps = [
        "//progress-bar:progress-bar",
        "//logger:logger",
    ],
    deps_query = "$declared_deps",
    labels = [],
)
