cxx_library(
    name = "builtin-color-util",
    srcs = [],
    headers = [],
    exported_headers = [
        "color.hpp",
    ],
    header_namespace = "utils/",
    preferred_linkage = "static",
    visibility = [
        "//progress-bar:progress-bar",
        "//logger:logger",
    ],
    labels = [],
)
